// <auto-generated />
using System;
using GoogleKeep.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GoogleKeep.Migrations
{
    [DbContext(typeof(NotesContext))]
    [Migration("20180802103828_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GoogleKeep.Models.CheckList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Item");

                    b.Property<int?>("NoteID");

                    b.HasKey("ID");

                    b.HasIndex("NoteID");

                    b.ToTable("CheckList");
                });

            modelBuilder.Entity("GoogleKeep.Models.Label", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int?>("NoteID");

                    b.HasKey("ID");

                    b.HasIndex("NoteID");

                    b.ToTable("Label");
                });

            modelBuilder.Entity("GoogleKeep.Models.Note", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsPinned");

                    b.Property<string>("Text");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("GoogleKeep.Models.CheckList", b =>
                {
                    b.HasOne("GoogleKeep.Models.Note")
                        .WithMany("Checklists")
                        .HasForeignKey("NoteID");
                });

            modelBuilder.Entity("GoogleKeep.Models.Label", b =>
                {
                    b.HasOne("GoogleKeep.Models.Note")
                        .WithMany("Labels")
                        .HasForeignKey("NoteID");
                });
#pragma warning restore 612, 618
        }
    }
}
